name: python3 test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - name: test
        run: find ./algorithms -name "*.py" | tr '\n' '\0' | xargs -0 -n1 python
