name: 'update readme'

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r ./gen_readme/requirements.txt
      - name: update README.md
        run: make build
      - name: Commit & Push
        run: |
          CHANGES=$(git status --porcelain)
          if [[ $CHANGES != '' ]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "update README.md"
            git push
          fi
